  const countryList = {
    AED: "AE",
    AFN: "AF",
    XCD: "AG",
    ALL: "AL",
    AMD: "AM",
    ANG: "AN",
    AOA: "AO",
    AQD: "AQ",
    ARS: "AR",
    AUD: "AU",
    AZN: "AZ",
    BAM: "BA",
    BBD: "BB",
    BDT: "BD",
    XOF: "BE",
    BGN: "BG",
    BHD: "BH",
    BIF: "BI",
    BMD: "BM",
    BND: "BN",
    BOB: "BO",
    BRL: "BR",
    BSD: "BS",
    NOK: "BV",
    BWP: "BW",
    BYR: "BY",
    BZD: "BZ",
    CAD: "CA",
    CDF: "CD",
    XAF: "CF",
    CHF: "CH",
    CLP: "CL",
    CNY: "CN",
    COP: "CO",
    CRC: "CR",
    CUP: "CU",
    CVE: "CV",
    CYP: "CY",
    CZK: "CZ",
    DJF: "DJ",
    DKK: "DK",
    DOP: "DO",
    DZD: "DZ",
    ECS: "EC",
    EEK: "EE",
    EGP: "EG",
    ETB: "ET",
    EUR: "FR",
    FJD: "FJ",
    FKP: "FK",
    GBP: "GB",
    GEL: "GE",
    GGP: "GG",
    GHS: "GH",
    GIP: "GI",
    GMD: "GM",
    GNF: "GN",
    GTQ: "GT",
    GYD: "GY",
    HKD: "HK",
    HNL: "HN",
    HRK: "HR",
    HTG: "HT",
    HUF: "HU",
    IDR: "ID",
    ILS: "IL",
    INR: "IN",
    IQD: "IQ",
    IRR: "IR",
    ISK: "IS",
    JMD: "JM",
    JOD: "JO",
    JPY: "JP",
    KES: "KE",
    KGS: "KG",
    KHR: "KH",
    KMF: "KM",
    KPW: "KP",
    KRW: "KR",
    KWD: "KW",
    KYD: "KY",
    KZT: "KZ",
    LAK: "LA",
    LBP: "LB",
    LKR: "LK",
    LRD: "LR",
    LSL: "LS",
    LTL: "LT",
    LVL: "LV",
    LYD: "LY",
    MAD: "MA",
    MDL: "MD",
    MGA: "MG",
    MKD: "MK",
    MMK: "MM",
    MNT: "MN",
    MOP: "MO",
    MRO: "MR",
    MTL: "MT",
    MUR: "MU",
    MVR: "MV",
    MWK: "MW",
    MXN: "MX",
    MYR: "MY",
    MZN: "MZ",
    NAD: "NA",
    XPF: "NC",
    NGN: "NG",
    NIO: "NI",
    NPR: "NP",
    NZD: "NZ",
    OMR: "OM",
    PAB: "PA",
    PEN: "PE",
    PGK: "PG",
    PHP: "PH",
    PKR: "PK",
    PLN: "PL",
    PYG: "PY",
    QAR: "QA",
    RON: "RO",
    RSD: "RS",
    RUB: "RU",
    RWF: "RW",
    SAR: "SA",
    SBD: "SB",
    SCR: "SC",
    SDG: "SD",
    SEK: "SE",
    SGD: "SG",
    SKK: "SK",
    SLL: "SL",
    SOS: "SO",
    SRD: "SR",
    STD: "ST",
    SVC: "SV",
    SYP: "SY",
    SZL: "SZ",
    THB: "TH",
    TJS: "TJ",
    TMT: "TM",
    TND: "TN",
    TOP: "TO",
    TRY: "TR",
    TTD: "TT",
    TWD: "TW",
    TZS: "TZ",
    UAH: "UA",
    UGX: "UG",
    USD: "US",
    UYU: "UY",
    UZS: "UZ",
    VEF: "VE",
    VND: "VN",
    VUV: "VU",
    YER: "YE",
    ZAR: "ZA",
    ZMK: "ZM",
    ZWD: "ZW",
  };
  
  const countryName = {
      AED: "United Arab Emirates Dirham - AED",
      AFN: "Afghan Afghani - AFN",
      XCD: "East Caribbean Dollar - XCD",
      ALL: "Albanian Lek - ALL",
      AMD: "Armenian Dram - AMD",
      ANG: "Netherlands Antillean Guilder - ANG",
      AOA: "Angolan Kwanza - AOA",
      AQD: "Antarctican Dollar - AQD",
      ARS: "Argentine Peso - ARS",
      AUD: "Australian Dollar - AUD",
      AZN: "Azerbaijani Manat - AZN",
      BAM: "Bosnia and Herzegovina Convertible Mark - BAM",
      BBD: "Barbadian Dollar - BBD",
      BDT: "Bangladeshi Taka - BDT",
      XOF: "West African CFA Franc - XOF",
      BGN: "Bulgarian Lev - BGN",
      BHD: "Bahraini Dinar - BHD",
      BIF: "Burundian Franc - BIF",
      BMD: "Bermudian Dollar - BMD",
      BND: "Brunei Dollar - BND",
      BOB: "Bolivian Boliviano - BOB",
      BRL: "Brazilian Real - BRL",
      BSD: "Bahamian Dollar - BSD",
      NOK: "Norwegian Krone - NOK",
      BWP: "Botswana Pula - BWP",
      BYR: "Belarusian Ruble - BYR",
      BZD: "Belize Dollar - BZD",
      CAD: "Canadian Dollar - CAD",
      CDF: "Congolese Franc - CDF",
      XAF: "Central African CFA Franc - XAF",
      CHF: "Swiss Franc - CHF",
      CLP: "Chilean Peso - CLP",
      CNY: "Chinese Yuan - CNY",
      COP: "Colombian Peso - COP",
      CRC: "Costa Rican Colón - CRC",
      CUP: "Cuban Peso - CUP",
      CVE: "Cape Verdean Escudo - CVE",
      CYP: "Cypriot Pound - CYP",
      CZK: "Czech Koruna - CZK",
      DJF: "Djiboutian Franc - DJF",
      DKK: "Danish Krone - DKK",
      DOP: "Dominican Peso - DOP",
      DZD: "Algerian Dinar - DZD",
      ECS: "Ecuadorian Sucre - ECS",
      EEK: "Estonian Kroon - EEK",
      EGP: "Egyptian Pound - EGP",
      ETB: "Ethiopian Birr - ETB",
      EUR: "Euro - EUR",
      FJD: "Fijian Dollar - FJD",
      FKP: "Falkland Islands Pound - FKP",
      GBP: "British Pound - GBP",
      GEL: "Georgian Lari - GEL",
      GGP: "Guernsey Pound - GGP",
      GHS: "Ghanaian Cedi - GHS",
      GIP: "Gibraltar Pound - GIP",
      GMD: "Gambian Dalasi - GMD",
      GNF: "Guinean Franc - GNF",
      GTQ: "Guatemalan Quetzal - GTQ",
      GYD: "Guyanese Dollar - GYD",
      HKD: "Hong Kong Dollar - HKD",
      HNL: "Honduran Lempira - HNL",
      HRK: "Croatian Kuna - HRK",
      HTG: "Haitian Gourde - HTG",
      HUF: "Hungarian Forint - HUF",
      IDR: "Indonesian Rupiah - IDR",
      ILS: "Israeli New Shekel - ILS",
      INR: "Indian Rupee - INR",
      IQD: "Iraqi Dinar - IQD",
      IRR: "Iranian Rial - IRR",
      ISK: "Icelandic Króna - ISK",
      JMD: "Jamaican Dollar - JMD",
      JOD: "Jordanian Dinar - JOD",
      JPY: "Japanese Yen - JPY",
      KES: "Kenyan Shilling - KES",
      KGS: "Kyrgyzstani Som - KGS",
      KHR: "Cambodian Riel - KHR",
      KMF: "Comorian Franc - KMF",
      KPW: "North Korean Won - KPW",
      KRW: "South Korean Won - KRW",
      KWD: "Kuwaiti Dinar - KWD",
      KYD: "Cayman Islands Dollar - KYD",
      KZT: "Kazakhstani Tenge - KZT",
      LAK: "Lao Kip - LAK",
      LBP: "Lebanese Pound - LBP",
      LKR: "Sri Lankan Rupee - LKR",
      LRD: "Liberian Dollar - LRD",
      LSL: "Lesotho Loti - LSL",
      LTL: "Lithuanian Litas - LTL",
      LVL: "Latvian Lats - LVL",
      LYD: "Libyan Dinar - LYD",
      MAD: "Moroccan Dirham - MAD",
      MDL: "Moldovan Leu - MDL",
      MGA: "Malagasy Ariary - MGA",
      MKD: "Macedonian Denar - MKD",
      MMK: "Myanmar Kyat - MMK",
      MNT: "Mongolian Tögrög - MNT",
      MOP: "Macanese Pataca - MOP",
      MRO: "Mauritanian Ouguiya - MRO",
      MTL: "Maltese Lira - MTL",
      MUR: "Mauritian Rupee - MUR",
      MVR: "Maldivian Rufiyaa - MVR",
      MWK: "Malawian Kwacha - MWK",
      MXN: "Mexican Peso - MXN",
      MYR: "Malaysian Ringgit - MYR",
      MZN: "Mozambican Metical - MZN",
      NAD: "Namibian Dollar - NAD",
      XPF: "CFP Franc - XPF",
      NGN: "Nigerian Naira - NGN",
      NIO: "Nicaraguan Córdoba - NIO",
      NPR: "Nepalese Rupee - NPR",
      NZD: "New Zealand Dollar - NZD",
      OMR: "Omani Rial - OMR",
      PAB: "Panamanian Balboa - PAB",
      PEN: "Peruvian Sol - PEN",
      PGK: "Papua New Guinean Kina - PGK",
      PHP: "Philippine Peso - PHP",
      PKR: "Pakistani Rupee - PKR",
      PLN: "Polish Złoty - PLN",
      PYG: "Paraguayan Guaraní - PYG",
      QAR: "Qatari Riyal - QAR",
      RON: "Romanian Leu - RON",
      RSD: "Serbian Dinar - RSD",
      RUB: "Russian Ruble - RUB",
      RWF: "Rwandan Franc - RWF",
      SAR: "Saudi Riyal - SAR",
      SBD: "Solomon Islands Dollar - SBD",
      SCR: "Seychellois Rupee - SCR",
      SDG: "Sudanese Pound - SDG",
      SEK: "Swedish Krona - SEK",
      SGD: "Singapore Dollar - SGD",
      SKK: "Slovak Koruna - SKK",
      SLL: "Sierra Leonean Leone - SLL",
      SOS: "Somali Shilling - SOS",
      SRD: "Surinamese Dollar - SRD",
      STD: "São Tomé and Príncipe Dobra - STD",
      SVC: "Salvadoran Colón - SVC",
      SYP: "Syrian Pound - SYP",
      SZL: "Swazi Lilangeni - SZL",
      THB: "Thai Baht - THB",
      TJS: "Tajikistani Somoni - TJS",
      TMT: "Turkmenistani Manat - TMT",
      TND: "Tunisian Dinar - TND",
      TOP: "Tongan Paʻanga - TOP",
      TRY: "Turkish Lira - TRY",
      TTD: "Trinidad and Tobago Dollar - TTD",
      TWD: "New Taiwan Dollar - TWD",
      TZS: "Tanzanian Shilling - TZS",
      UAH: "Ukrainian Hryvnia - UAH",
      UGX: "Ugandan Shilling - UGX",
      USD: "United States Dollar - USD",
      UYU: "Uruguayan Peso - UYU",
      UZS: "Uzbekistani Som - UZS",
      VEF: "Venezuelan Bolívar - VEF",
      VND: "Vietnamese Đồng - VND",
      VUV: "Vanuatu Vatu - VUV",
      YER: "Yemeni Rial - YER",
      ZAR: "South African Rand - ZAR",
      ZMK: "Zambian Kwacha - ZMK",
      ZWD: "Zimbabwean Dollar - ZWD"
    };
    
  //  export default {countryList,countryName};
   export {countryList,countryName};